name: "unit tests"

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
    - name: checkout repository
      uses: actions/checkout@v3

    - name: set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: install dependencies
      run: bundle install

    - name: run rspec
      run: |
        bash -c "
          bundle exec rspec spec
        "

    - name: Upload Sarif output
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: rubocop.sarif
